create table access_log (
        id char(19) ,
        agent varchar(255) ,
        bytes_sent int unsigned ,
        child_pid smallint unsigned,
        cookie varchar(255),
        machine_id varchar(25),
        request_file varchar(255),
        referer varchar(255) ,
        remote_host varchar(50) ,
        remote_logname varchar(50) ,
        remote_user varchar(50) ,
        request_duration smallint unsigned ,
        request_line varchar(255),
        request_method varchar(10) ,
        request_protocol varchar(10) ,
        request_time char(28),
        request_uri varchar(255),
        request_args varchar(255),
        server_port smallint unsigned,
        ssl_cipher varchar(25),
        ssl_keysize smallint unsigned,
        ssl_maxkeysize smallint unsigned,
        status smallint unsigned ,
        time_stamp int unsigned ,
        virtual_host varchar(255),
		bc_name varchar(100),
		bc_mail varchar(100),
		bc_location varchar(100),
		bc_comment varchar(512),
		bc_what varchar(256),
		bc_city varchar(128),
		bc_countryCode varchar(10),
		bc_countryName varchar(64),
		bc_latitude double,
		bc_longitude double,
		bc_region varchar(10)
);
